name: Mi Primer Workflow
on: workflow_dispatch
jobs:
    saludar:
        runs-on: ubuntu-latest
        steps:
            - name: Decir Hola
              run: echo "Hola Mundo"
            - name: Dame la fecha
              run: date